import { useParams } from 'react-router-dom'
import { CrudManager, type FieldDef } from '@/pages/admin/CrudManager'

const published = { name: 'is_published', label: 'Published', type: 'checkbox' } as const

const resources: Record<string, { title: string; table: string; orderBy: string; labelKey: string; fields: FieldDef[]; blank: Record<string, unknown> }> = {
  workshops: {
    title: 'Workshops',
    table: 'workshops',
    orderBy: 'starts_at',
    labelKey: 'title',
    fields: [
      { name: 'slug', label: 'Slug', type: 'text', required: true },
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'summary', label: 'Summary', type: 'textarea', required: true },
      { name: 'description', label: 'Description', type: 'textarea', required: true },
      { name: 'starts_at', label: 'Starts', type: 'datetime' },
      { name: 'mode', label: 'Mode', type: 'text', required: true },
      { name: 'location', label: 'Location', type: 'text' },
      { name: 'cover_url', label: 'Cover image URL', type: 'text' },
      { name: 'price_ngn', label: 'Price (NGN)', type: 'number', required: true },
      { name: 'seats', label: 'Seats', type: 'number' },
      { name: 'instructor', label: 'Instructor', type: 'text' },
      { name: 'registration_status', label: 'Registration status', type: 'text', required: true },
      published,
    ],
    blank: { slug: '', title: '', summary: '', description: '', starts_at: '', mode: 'Online', location: '', cover_url: '', price_ngn: 0, seats: '', instructor: '', registration_status: 'open', is_published: true },
  },
  faqs: {
    title: 'FAQs',
    table: 'faqs',
    orderBy: 'sort_order',
    labelKey: 'question',
    fields: [
      { name: 'question', label: 'Question', type: 'text', required: true },
      { name: 'answer', label: 'Answer', type: 'textarea', required: true },
      { name: 'topic', label: 'Topic', type: 'text', required: true },
      { name: 'sort_order', label: 'Sort order', type: 'number', required: true },
      published,
    ],
    blank: { question: '', answer: '', topic: 'General', sort_order: 0, is_published: true },
  },
  testimonials: {
    title: 'Testimonials',
    table: 'testimonials',
    orderBy: 'sort_order',
    labelKey: 'name',
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'role', label: 'Role', type: 'text', required: true },
      { name: 'program_label', label: 'Program', type: 'text' },
      { name: 'quote', label: 'Quote', type: 'textarea', required: true },
      { name: 'rating', label: 'Rating', type: 'number', required: true },
      { name: 'sort_order', label: 'Sort order', type: 'number', required: true },
      published,
    ],
    blank: { name: '', role: 'Program student', program_label: '', quote: '', rating: 5, sort_order: 0, is_published: false },
  },
  mentors: {
    title: 'Mentors',
    table: 'mentors',
    orderBy: 'sort_order',
    labelKey: 'name',
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'focus', label: 'Focus', type: 'text', required: true },
      { name: 'bio', label: 'Bio', type: 'textarea', required: true },
      { name: 'sort_order', label: 'Sort order', type: 'number', required: true },
      published,
    ],
    blank: { name: '', title: '', focus: '', bio: '', sort_order: 0, is_published: false },
  },
  journey: {
    title: 'Learning journey',
    table: 'journey_steps',
    orderBy: 'sort_order',
    labelKey: 'title',
    fields: [
      { name: 'step_number', label: 'Step number', type: 'number', required: true },
      { name: 'phase', label: 'Phase', type: 'text', required: true },
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea', required: true },
      { name: 'sort_order', label: 'Sort order', type: 'number', required: true },
    ],
    blank: { step_number: 1, phase: '', title: '', description: '', sort_order: 1 },
  },
  community: {
    title: 'Community',
    table: 'community_posts',
    orderBy: 'sort_order',
    labelKey: 'title',
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'body', label: 'Body', type: 'textarea', required: true },
      { name: 'kind', label: 'Kind', type: 'text', required: true },
      { name: 'author_name', label: 'Author', type: 'text' },
      { name: 'sort_order', label: 'Sort order', type: 'number', required: true },
      published,
    ],
    blank: { title: '', body: '', kind: 'Community', author_name: '', sort_order: 0, is_published: true },
  },
  'community-links': {
    title: 'Community links',
    table: 'community_links',
    orderBy: 'sort_order',
    labelKey: 'label',
    fields: [
      { name: 'platform', label: 'Platform', type: 'text', required: true },
      { name: 'label', label: 'Label', type: 'text', required: true },
      { name: 'url', label: 'URL', type: 'text', required: true },
      { name: 'sort_order', label: 'Sort order', type: 'number', required: true },
      published,
    ],
    blank: { platform: 'WhatsApp', label: '', url: '', sort_order: 0, is_published: false },
  },
  social: {
    title: 'Social links',
    table: 'social_links',
    orderBy: 'sort_order',
    labelKey: 'platform',
    fields: [
      { name: 'platform', label: 'Platform', type: 'text', required: true },
      { name: 'url', label: 'URL', type: 'text', required: true },
      { name: 'sort_order', label: 'Sort order', type: 'number', required: true },
      published,
    ],
    blank: { platform: '', url: '', sort_order: 0, is_published: false },
  },
  settings: {
    title: 'Site settings',
    table: 'site_settings',
    orderBy: 'key',
    labelKey: 'key',
    fields: [
      { name: 'key', label: 'Key', type: 'text', required: true },
      { name: 'value', label: 'Value', type: 'text', required: true },
    ],
    blank: { key: '', value: '' },
  },
  professional: {
    title: 'Professional programs',
    table: 'professional_programs',
    orderBy: 'sort_order',
    labelKey: 'title',
    fields: [
      { name: 'slug', label: 'Slug', type: 'text', required: true },
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea', required: true },
      { name: 'duration_label', label: 'Duration', type: 'text' },
      { name: 'price', label: 'Price', type: 'number' },
      { name: 'requirements', label: 'Requirements', type: 'textarea' },
      { name: 'application_process', label: 'Application process', type: 'textarea' },
      { name: 'status', label: 'Status', type: 'text', required: true },
      { name: 'starts_on', label: 'Start date', type: 'text' },
      { name: 'ends_on', label: 'End date', type: 'text' },
      { name: 'sort_order', label: 'Sort order', type: 'number', required: true },
      published,
    ],
    blank: { slug: '', title: '', description: '', duration_label: '', price: '', requirements: '', application_process: '', status: 'open', starts_on: '', ends_on: '', sort_order: 0, is_published: false },
  },
  mentorship: {
    title: 'Mentorship programs',
    table: 'mentorship_programs',
    orderBy: 'sort_order',
    labelKey: 'title',
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea', required: true },
      { name: 'availability', label: 'Availability', type: 'text' },
      { name: 'application_status', label: 'Application status', type: 'text', required: true },
      { name: 'sort_order', label: 'Sort order', type: 'number', required: true },
      published,
    ],
    blank: { title: '', description: '', availability: '', application_status: 'open', sort_order: 0, is_published: false },
  },
  roadmaps: {
    title: 'Course roadmaps',
    table: 'course_roadmaps',
    orderBy: 'sort_order',
    labelKey: 'title',
    fields: [
      { name: 'course_category_id', label: 'Course category id', type: 'text', required: true },
      { name: 'week_number', label: 'Week number', type: 'number', required: true },
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea', required: true },
      { name: 'sort_order', label: 'Sort order', type: 'number', required: true },
    ],
    blank: { course_category_id: '', week_number: 1, title: '', description: '', sort_order: 1 },
  },
  projects: {
    title: 'Course projects',
    table: 'course_projects',
    orderBy: 'sort_order',
    labelKey: 'title',
    fields: [
      { name: 'course_category_id', label: 'Course category id', type: 'text', required: true },
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea', required: true },
      { name: 'difficulty', label: 'Difficulty', type: 'text' },
      { name: 'skills', label: 'Skills covered', type: 'text' },
      { name: 'outcome', label: 'Expected outcome', type: 'textarea' },
      { name: 'sort_order', label: 'Sort order', type: 'number', required: true },
    ],
    blank: { course_category_id: '', title: '', description: '', difficulty: '', skills: '', outcome: '', sort_order: 1 },
  },
  announcements: {
    title: 'Announcements',
    table: 'announcements',
    orderBy: 'created_at',
    labelKey: 'title',
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'body', label: 'Body', type: 'textarea', required: true },
      published,
    ],
    blank: { title: '', body: '', is_published: false },
  },
  resources: {
    title: 'Learning resources',
    table: 'learning_resources',
    orderBy: 'sort_order',
    labelKey: 'title',
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'link_url', label: 'Link', type: 'text' },
      { name: 'course_category_id', label: 'Course category id', type: 'text' },
      { name: 'sort_order', label: 'Sort order', type: 'number', required: true },
      published,
    ],
    blank: { title: '', description: '', link_url: '', course_category_id: '', sort_order: 0, is_published: false },
  },
  certificates: {
    title: 'Certificates',
    table: 'certificates',
    orderBy: 'issued_on',
    labelKey: 'certificate_number',
    fields: [
      { name: 'student_id', label: 'Student id', type: 'text', required: true },
      { name: 'enrollment_id', label: 'Enrollment id', type: 'text' },
      { name: 'certificate_number', label: 'Certificate number', type: 'text', required: true },
      { name: 'student_name', label: 'Student name', type: 'text', required: true },
      { name: 'program_name', label: 'Program', type: 'text', required: true },
      { name: 'issued_on', label: 'Issue date', type: 'text', required: true },
      { name: 'status', label: 'Status', type: 'text', required: true },
      { name: 'file_url', label: 'File URL', type: 'text' },
    ],
    blank: { student_id: '', enrollment_id: '', certificate_number: '', student_name: '', program_name: '', issued_on: '', status: 'valid', file_url: '' },
  },
  students: {
    title: 'Students',
    table: 'profiles',
    orderBy: 'created_at',
    labelKey: 'full_name',
    fields: [
      { name: 'full_name', label: 'Full name', type: 'text', required: true },
      { name: 'email', label: 'Email', type: 'text', required: true },
      { name: 'phone', label: 'WhatsApp', type: 'text' },
      { name: 'role', label: 'Role', type: 'text', required: true },
    ],
    blank: { full_name: '', email: '', phone: '', role: 'student' },
  },
}

export function AdminRecords() {
  const { resource = '' } = useParams()
  const config = resources[resource]
  if (!config) return <p>That admin section does not exist.</p>
  return <CrudManager {...config} allowCreate={resource !== 'students'} />
}
